name: supabase_model_generator
description: A powerful code generator that automatically creates Dart models and repositories from your Supabase database schema, streamlining your development workflow.
version: 0.1.0
repository: https://github.com/yourusername/supabase_model_generator
homepage: https://github.com/yourusername/supabase_model_generator
issue_tracker: https://github.com/yourusername/supabase_model_generator/issues
documentation: https://github.com/yourusername/supabase_model_generator#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

builders:
  supabase_model_generator:
    import: "package:supabase_model_generator/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: {".dart": [".model.dart", ".repository.dart"]}
    auto_apply: dependents
    build_to: source

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  analyzer: ^5.7.1
  postgres: ^2.6.1
  yaml: ^3.1.1
  path: ^1.8.3
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  collection: ^1.19.1
  built_collection: ^5.1.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.23.1
  lints: ^2.0.1
  supabase: ^2.0.8  # For testing with the Dart client