name: supabase_model_generator
description: A code generator for Dart models and repositories from Supabase schema.
version: 0.1.0
homepage: https://your-repository-url.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  analyzer: ^5.7.1
  postgres: ^2.6.1
  yaml: ^3.1.1
  path: ^1.8.3
  code_builder: ^4.4.0
  dart_style: ^2.2.4

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.23.1
  lints: ^2.0.1